import turtle
a = turtle.Turtle()
a.speed(0)
turtle.setup(800, 600)
a.speed(-5)
a.up()

def my_goto(X, Y):
    a.pencolor("orange")
    a.penup()
    a.goto(X, Y)
    a.pendown()

def round_rectangle(center_X, center_Y, width, height, cornersize):
    a.up()
    a.goto(center_X-width/2+cornersize, center_Y-height/2)
    a.down()
    for i in range(2):
        a.fillcolor("black")
        a.begin_fill()
        a.fd(width-2*cornersize)
        a.circle(cornersize, 90)
        a.fd(height-2*cornersize)
        a.circle(cornersize, 90)
        a.end_fill()

        round_rectangle(0, 0, 200, 300, 80)
        a.fillcolor("black")
        a.begin_fill()
        a.goto(-35, 40)
        a.fillcolor("white")
        a.begin_fill()
        a.forward(80)
        a.left(90)
        a.forward(10)
        a.left(90)
        a.forward(80)
        a.left(90)
        a.forward(10)
        a.left(90)

        a.goto(-35, 80)
        a.forward(80)
        a.left(90)
        a.forward(10)
        a.left(90)
        a.forward(80)
        a.left(90)
        a.forward(10)
        a.left(90)

        a.goto(-35, 60)
        a.forward(80)
        a.left(90)
        a.forward(10)
        a.left(90)
        a.forward(80)
        a.left(90)
        a.forward(10)
        a.left(90)

        a.end_fill()
        a.fillcolor("red")
        a.begin_fill()
        a.goto(5, 50)
        a.penup()
        a.circle(15)
        a.pendown()
        a.end_fill()

        a.goto(-150, -175)
        a.begin_fill()
        a.pencolor("black")
        a.fillcolor("black")
        round_rectangle(90, -125, 600, 100, 50)
        a.begin_fill()
        a.goto(-70, 175)
        a.setheading(110)
        a.circle(80, -100)
        a.goto(140, -280)
        a.setheading(350)
        a.circle(80, -100)
        a.end_fill()
